name: stage_craft
description: Develop and live test your UI widgets on a stage.
repository: https://github.com/robiness/stage_craft
issue_tracker: https://github.com/robiness/stage_craft/issues

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  flex_color_picker: ^3.4.1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  spot: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0


flutter:

  uses-material-design: true
